### ISSUE TITLE
Dockerising Data Ingestion 

### ISSUE THREAD

**Issue by Invictus17** [airavata-courses/DevoTeam#28]
Hi Team,
I'm facing the following error while dockerirsing the Data Ingestion service. Please have a look.

Error:
data-ingestion_1   | Data Ingestion service waiting for messages
data-ingestion_1   | Traceback (most recent call last):
data-ingestion_1   |   File "./service.py", line 9, in <module>
data-ingestion_1   |     connection = pika.BlockingConnection(pika.ConnectionParameters('rabbitmq-server', 5672))
data-ingestion_1   |   File "/usr/local/lib/python3.8/site-packages/pika/adapters/blocking_connection.py", line 359, in __init__
data-ingestion_1   |     self._impl = self._create_connection(parameters, _impl_class)
data-ingestion_1   |   File "/usr/local/lib/python3.8/site-packages/pika/adapters/blocking_connection.py", line 450, in _create_connection
data-ingestion_1   |     raise self._reap_last_connection_workflow_error(error)
data-ingestion_1   | pika.exceptions.AMQPConnectionError

**Comment by Invictus17** [comment]
You can find the files in the Develop_2 branch

**Comment by Invictus17** [comment]
Closing the issue referencing commit a83ce83d9efdd59e8db1b65425ffb26c529e0e51
